package org.example.project_manager_dashboard.models;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "daily_counter")
public class DailyCounter {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    @Column(name = "counter_value")
    private Integer counterValue;

    @Column(name = "last_reset_date")
    private LocalDate lastResetDate;
    // Getters and setters (generated by Lombok)

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid") // This should match the @Id column name in User entity
    private User user;
}
